# Generated by Django 4.2.3 on 2024-05-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antifraud',
            name='max_sequence_unapproved',
            field=models.IntegerField(default=0),
        ),
    ]
